"""Loads the real platform seed tree (`package/seeds/platform`) through the
loader against a capturing fake DB and asserts the expected platform inventory.

The loader must produce the expected platform collections, artifacts, and
containment edges from the declarative seed tree. Identity converges via
uuid5 (registry empty in tests), so ids are deterministic from the instance
namespace.
"""
from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from mantle.services.seed_provisioning import loader

# Root resolved through the one helper so the conftest skip gate and this test cannot disagree:
# a mismatch here reads as an empty dir rather than the real tree's files (see _package_root).
from ._package_root import seeds_root  # noqa: E402
PLATFORM_ROOT = seeds_root() / "platform"


@pytest.fixture(autouse=True)
def _clear_registry():
    from mantle.services import platform_topology

    platform_topology.clear_registry()
    with patch("mantle.services.seed_provisioning.loader._persist_seed_ids"):
        yield
    platform_topology.clear_registry()


def _load(tmp_path, monkeypatch):
    monkeypatch.setenv("KEYS_DIR", str(tmp_path / "keys"))
    cap = {"coll": [], "art": [], "edge": []}
    with (
        patch("mantle.services.seed_provisioning.loader.db_get_collection_by_id", return_value=None),
        patch("mantle.services.seed_provisioning.loader.db_create_collection",
              side_effect=lambda db, c: cap["coll"].append(c)),
        patch("mantle.services.seed_provisioning.loader.db_get_artifact", return_value=None),
        patch("mantle.services.seed_provisioning.loader.db_create_artifact",
              side_effect=lambda db, a: cap["art"].append(a)),
        patch("mantle.services.seed_provisioning.loader.db_get_edge", return_value=None),
        patch("mantle.services.seed_provisioning.loader.db_add_artifact_to_collection",
              side_effect=lambda db, cid, rid, ok=None, **kw: cap["edge"].append(
                  (cid, rid, kw.get("relationship")))),
    ):
        report = loader.seed_from_artifacts(MagicMock(), PLATFORM_ROOT)
    return report, cap


def _id(slug: str) -> str:
    return loader.derive_uuid(loader.get_instance_namespace(), "agience", slug)


_EXPECTED_COLLECTIONS = [
    "agience-authorities", "agience-hosts", "agience-resources",
    "agience-package-registry", "agience-inbox-seeds",
    "agience-seeds-start-here", "agience-seeds-platform-artifacts",
    "agience-seeds-all-servers", "agience-seeds-all-tools", "agience-seeds-agents",
    "agience-anchorset",
]

_PERSONAS = ("aria", "astra", "sage", "iris", "ophan", "seraph", "lumen")

_EXPECTED_ARTIFACTS = [
    "agience-authority-current-instance", "agience-host-current-instance",
    "agience-agency-platform", "agience-beam",
    *(f"agience-agent-{s}" for s in _PERSONAS),
    *(f"agience-server-{s}" for s in _PERSONAS),
    *(f"agience-doc-{s}" for s in ("welcome", "cards", "collections", "agents")),
    *(f"agience-tools-{s}" for s in _PERSONAS),
    "agience-search-standard",
]


def test_platform_tree_loads_without_errors(tmp_path, monkeypatch):
    report, cap = _load(tmp_path, monkeypatch)
    assert report.errors == []
    # 11 collections (incl. the AnchorSet); 30 artifacts (2 singletons + 7 agents
    # + 1 agency + 8 servers + 4 start-here docs + 7 tool catalogs + 1 standard
    # search flavor). There are no LLM connections or their collection (the
    # no-models rule). The AnchorSet is seeded empty — its anchor artifacts
    # are generated by the mantle bootstrap, not the declarative seed tree.
    # (People is NOT here — it's created at runtime, outside the platform-registry.)
    assert len(cap["coll"]) == len(_EXPECTED_COLLECTIONS) == 11
    assert len(cap["art"]) == len(_EXPECTED_ARTIFACTS) == 30


def test_platform_tree_creates_expected_collections(tmp_path, monkeypatch):
    _, cap = _load(tmp_path, monkeypatch)
    created = {c.id for c in cap["coll"]}
    for slug in _EXPECTED_COLLECTIONS:
        assert _id(slug) in created, f"missing collection {slug}"


def test_platform_tree_creates_expected_artifacts(tmp_path, monkeypatch):
    _, cap = _load(tmp_path, monkeypatch)
    created = {a.id for a in cap["art"]}
    for slug in _EXPECTED_ARTIFACTS:
        assert _id(slug) in created, f"missing artifact {slug}"


def test_platform_tree_containment_and_membership_edges(tmp_path, monkeypatch):
    _, cap = _load(tmp_path, monkeypatch)
    edges = {(cid, rid) for (cid, rid, _rel) in cap["edge"]}
    # Aria agent: origin in resources, linked into agents collection.
    assert (_id("agience-resources"), _id("agience-agent-aria")) in edges
    assert (_id("agience-seeds-agents"), _id("agience-agent-aria")) in edges
    # Server record in the all-servers collection.
    assert (_id("agience-seeds-all-servers"), _id("agience-server-lumen")) in edges
    # Authority + host artifacts also linked into platform-artifacts.
    assert (_id("agience-seeds-platform-artifacts"), _id("agience-authority-current-instance")) in edges
    assert (_id("agience-seeds-platform-artifacts"), _id("agience-host-current-instance")) in edges
    # Collection-into-collection membership.
    assert (_id("agience-inbox-seeds"), _id("agience-seeds-start-here")) in edges
    assert (_id("agience-seeds-platform-artifacts"), _id("agience-seeds-all-servers")) in edges


def test_platform_tree_agent_context_refs_resolved(tmp_path, monkeypatch):
    """Cross-artifact refs in agent context (server_id, host, authority) resolve
    to UUIDs — never left as `namespace/slug` strings."""
    import json

    _, cap = _load(tmp_path, monkeypatch)
    aria = next(a for a in cap["art"] if a.id == _id("agience-agent-aria"))
    ctx = json.loads(aria.context)
    assert ctx["agent"]["server_id"] == _id("agience-server-aria")
    assert ctx["agent"]["host_artifact_id"] == _id("agience-host-current-instance")
    assert ctx["agent"]["authority_artifact_id"] == _id("agience-authority-current-instance")
    assert "/" not in ctx["agent"]["server_id"]
