"""Build the single-file `agience` executable.

    python packaging/build.py [--onedir] [--clean]

What this produces: one file carrying mantle, prism, FastAPI, uvicorn and the crypto stack, so an
install resolves nothing at install time. `agience-prism-py` is not on PyPI, which is why
`pip install -e '.[service]'` fails on a machine that is not a developer's, and vendoring prism here
takes the sibling-checkout assumption out of the delivery path.

The digest is the artifact. This prints the sha256 of what it built and stamps the same build id
into the binary, so `agience version` and the file on disk name the same thing. The fleet's
promotion rule is "the digest is the artifact — nothing in this path accepts a tag", so a build that
cannot be identified by content cannot participate in it, or be served by digest from a node's own
CAS.

Hidden imports are required. Mantle resolves several things by name at runtime — the routers it
mounts, the ontology host named by `MANTLE_ONTOLOGY_HOST`, uvicorn's protocol implementations —
and PyInstaller's static analysis sees none of them. The failure mode is not a build error but a
binary that starts and then 500s on the first request touching the module nobody collected.
`--collect-all` on the two first-party packages is blunt for that
reason — a few MB against a class of bug that only appears in the shipped artifact.
"""
from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
DIST = REPO / "dist"
WORK = REPO / "build" / "pyinstaller"


def _git(*args: str) -> str:
    try:
        return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def _version() -> str:
    try:
        import tomllib
        return tomllib.loads((REPO / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]
    except Exception:
        return "0.0.0"


def write_build_info() -> dict:
    """Stamp what this build IS, before building it.

    `dirty` is recorded rather than refused. A build from a modified tree is a legitimate thing to
    make and an illegitimate thing to promote, and those are different decisions belonging to
    different people. Recorded, the fact travels with the artifact to whoever makes the second
    one.
    """
    info = {
        "version": _version(),
        "built": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "commit": _git("rev-parse", "--short", "HEAD"),
        "dirty": bool(_git("status", "--porcelain")),
    }
    (HERE / "agience_build_info.py").write_text(
        "# GENERATED BY packaging/build.py — do not edit, do not commit a stale copy.\n"
        f"BUILD_INFO = {info!r}\n",
        encoding="utf-8",
    )
    return info


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--onedir", action="store_true", help="a directory instead of one file (starts faster, easier to inspect)")
    ap.add_argument("--clean", action="store_true", help="discard PyInstaller's cache first")
    args = ap.parse_args()

    info = write_build_info()
    print(f"building agience {info['version']} ({info['commit']}{'-dirty' if info['dirty'] else ''})")

    cmd = [
        sys.executable, "-m", "PyInstaller",
        "--noconfirm",
        "--name", "agience",
        "--distpath", str(DIST),
        "--workpath", str(WORK),
        "--specpath", str(WORK),
        "--onedir" if args.onedir else "--onefile",
        "--console",
        # The first-party packages, whole. See the note at the top of this file.
        "--collect-all", "mantle",
        "--collect-all", "prism",
        # Resolved by name at runtime by uvicorn/starlette, invisible to static analysis.
        "--collect-submodules", "uvicorn",
        "--hidden-import", "uvicorn.logging",
        "--hidden-import", "uvicorn.loops.auto",
        "--hidden-import", "uvicorn.protocols.http.auto",
        "--hidden-import", "uvicorn.protocols.websockets.auto",
        "--hidden-import", "uvicorn.lifespan.on",
        # `agience_build_info` sits beside the entry script; PyInstaller puts that directory on the
        # path, but it is imported inside a try/except so nothing here fails loudly if it moves.
        "--paths", str(HERE),
        str(HERE / "agience_node.py"),
    ]
    if args.clean:
        cmd.insert(3, "--clean")
        shutil.rmtree(WORK, ignore_errors=True)

    print("  " + " ".join(cmd[2:]))
    rc = subprocess.call(cmd)
    if rc != 0:
        print(f"\nPyInstaller failed ({rc})", file=sys.stderr)
        return rc

    exe = DIST / ("agience" + (".exe" if sys.platform == "win32" else ""))
    if args.onedir:
        exe = DIST / "agience" / ("agience" + (".exe" if sys.platform == "win32" else ""))
    if not exe.exists():
        print(f"\nbuild reported success but {exe} is not there", file=sys.stderr)
        return 1

    digest = hashlib.sha256(exe.read_bytes()).hexdigest()
    size_mb = exe.stat().st_size / 1e6
    print(f"\n  {exe}")
    print(f"  {size_mb:.1f} MB")
    print(f"  sha256:{digest}")
    (exe.parent / f"{exe.name}.sha256").write_text(f"sha256:{digest}  {exe.name}\n", encoding="utf-8")
    print(f"\n  verify it:  {exe} version")
    return 0


if __name__ == "__main__":
    sys.exit(main())
